version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eventflow
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  event-flow:
    build: .
    container_name: event-flow
    volumes:
      - ./services/backend/event-flow:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_volume_local:


